---
title: "Financial"
format: html
editor: visual
---

```{r message = FALSE}

library(tidyverse)
library(readr)
library(rvest)
library(httr)
library(xml2)
```

## Scraping Function

```{r}
#|: function-to-scrape-tabular-financial-data-from-yahoo-finance
# returns a df that is ready for analysis
# if you leave the num_obs argument NULL, the scrape function will scrape as much data as it can from the given url
# file is the name the resulting df will be saved as

scrape_yahoo <- function(url, file, num_obs) {
  scrape(url, file, num_obs)
  df <- read_csv(
    file.path(
      dirname(getwd()),
      "data",
      file
    )
  )
  df <- df[-c(1)]
  df <- df |> 
    dplyr::rename(
      Date = 1, 
      Open = 2, 
      High = 3, 
      Low = 4,
      Close = 5, 
      Adj_Close = 6, 
      Volume = 7
    )
  return(df)
}
```

## Africa

```{r}

```

## Asia

```{r}

```

## Europe

```{r}

#|: austria
url = 'https://finance.yahoo.com/quote/%5EATX/history?p=%5EATX'
file = "Austria.csv"
num_obs =  NULL
austria <- scrape_yahoo(url, file, num_obs)
view(austria)

#|: belgium
url = 'https://finance.yahoo.com/quote/%5EBFX/history?p=%5EBFX'
file = "Belgium.csv"
num_obs =  NULL
belgium <- scrape_yahoo(url, file, num_obs)
view(belgium)

#|: denmark
url = 'https://finance.yahoo.com/quote/%5EOMXC25/history?p=%5EOMXC25'
file = "Denmark.csv"
num_obs =  NULL
denmark <- scrape_yahoo(url, file, num_obs)
view(denmark)

#|: finland
url = 'https://finance.yahoo.com/quote/%5EOMXH25/history?p=%5EOMXH25'
file = "Finland.csv"
num_obs =  NULL
finland <- scrape_yahoo(url, file, num_obs)
view(finland)

#|: france

# old way of webscraping
# france <- read_html("https://finance.yahoo.com/quote/%5EFCHI/history?period1=636249600&period2=1689033600&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true") |> 
#   html_table(fill = TRUE)
# view(france)

# new way of webscraping (using selenium)
url = 'https://finance.yahoo.com/quote/%5EFCHI/history?period1=636249600&period2=1689206400&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true'
file = "scrape.csv"
num_obs = 100
france <- scrape_yahoo(url, file, num_obs)
view(france)

#|: germany
url = 'https://finance.yahoo.com/quote/DAX/history?p=DAX'
file = "Germany.csv"
num_obs =  NULL
germany <- scrape_yahoo(url, file, num_obs)
view(germany)
```

## Oceania

```{r}
```

## North America

```{r}

```

## South America

```{r}

```
